Feat/156980247/build globalclockservice
rudxde/photomx pull request #16
Opened 2018-05-16 06:26 UTC by stovemeerkat

2018-05-16 06:27 UTC, stovemeerkat commented on front/src/app/core/services/globalclock/globalclockservice.service.ts
> +    this.timer = setInterval(this.tick, 200);  // TODO: delay is currently quite arbitrary
Delay value probably needs to be changed...

2018-05-16 11:48 UTC, rudxde requested changes

2018-05-16 11:48 UTC, rudxde commented on front/src/app/core/services/globalclock/globalclock.service.spec.ts
> +import { TestBed, inject } from '@angular/core/testing';
i think we don't need a empty test yet.

2018-05-16 11:48 UTC, rudxde commented on front/src/app/core/services/globalclock/globalclock.service.ts
> +    this.timer = setInterval(this.tick, 200);  // TODO: delay is currently quite arbitrary
i think a value of 1600ms should be enough.

2018-05-16 11:48 UTC, rudxde commented on front/src/app/core/services/globalclock/globalclock.service.ts
> +  constructor(fixtureService: FixtureService, artnetService: ArtnetService) {
you can declare the arguments as private, then you don't need to define them as extra variables!

2018-05-16 11:53 UTC, stovemeerkat commented on front/src/app/core/services/globalclock/globalclock.service.spec.ts
> +import { TestBed, inject } from '@angular/core/testing';
That's just what ng g generated...

2018-05-16 13:49 UTC, stovemeerkat commented
Implemented all changes.

2018-05-22 10:45 UTC, rudxde approved these changes

2018-05-22 10:45 UTC, merged